"""add landscape and description fields

Revision ID: 1544be55e36c
Revises: 
Create Date: 2015-08-28 16:49:59.216237

"""

# revision identifiers, used by Alembic.
revision = '1544be55e36c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PiUrl', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('PiUrl', sa.Column('landscape', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PiUrl', 'landscape')
    op.drop_column('PiUrl', 'description')
    ### end Alembic commands ###
