"""Extend db to include picture

Revision ID: 25a9a37f3c5f
Revises: 2345bcfeaced
Create Date: 2015-08-31 17:02:25.417938

"""

# revision identifiers, used by Alembic.
revision = '25a9a37f3c5f'
down_revision = '2345bcfeaced'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PiScreens',
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('image', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PiScreens')
    ### end Alembic commands ###
