"""Add boolean to trigger browser vs custom command

Revision ID: 2a8cd0bdebc1
Revises: 43e4ec819875
Create Date: 2015-09-25 01:07:03.902487

"""

# revision identifiers, used by Alembic.
revision = '2a8cd0bdebc1'
down_revision = '43e4ec819875'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PiUrl', sa.Column('browser', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PiUrl', 'browser')
    ### end Alembic commands ###
