"""Add tag table

Revision ID: 3788bc583f5f
Revises: 2afbc7d30a21
Create Date: 2015-09-11 13:37:28.739762

"""

# revision identifiers, used by Alembic.
revision = '3788bc583f5f'
down_revision = '2afbc7d30a21'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_taglist', 'Tags', ['tag', 'uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_taglist', table_name='Tags')
    op.drop_table('Tags')
    ### end Alembic commands ###
