"""add requested_commands to model

Revision ID: 43e4ec819875
Revises: 4c4654abd663
Create Date: 2015-09-16 08:08:10.605441

"""

# revision identifiers, used by Alembic.
revision = '43e4ec819875'
down_revision = '4c4654abd663'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PiUrl', sa.Column('requested_commands', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PiUrl', 'requested_commands')
    ### end Alembic commands ###
