"""create a relationship between tags and pis

Revision ID: 4c4654abd663
Revises: 3788bc583f5f
Create Date: 2015-09-11 17:59:53.166304

"""

# revision identifiers, used by Alembic.
revision = '4c4654abd663'
down_revision = '3788bc583f5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Tags', 'PiUrl', ['uuid'], ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tags', type_='foreignkey')
    ### end Alembic commands ###
