#!/usr/bin/env bash
sleep 5
MAC=$(ip link show eth0 | grep ether|awk '{print $2}')
BASEURL="http://pi_director"
BROWSER=$(curl ${BASEURL}/api/v1/cache/${MAC} 2>/dev/null|python -c 'import sys,json; print json.load(sys.stdin)["browser"]')
CMD=$(curl ${BASEURL}/api/v1/cache/${MAC} 2>/dev/null|python -c 'import sys,json; print json.load(sys.stdin)["url"]')


unclutter &
matchbox-window-manager &

if [[ "$BROWSER" == "True" ]]
then
    #if iceweasel is killed, it sometimes thinks it should remember crashed tabs.  It shouldn't.
    rm -rf ~/.mozilla/firefox >> /dev/null 2>&1

    iceweasel ${BASEURL}/go/${MAC} &
    sleep 10
    xdotool key F11
else
    $CMD
fi

~/keydown.sh
